version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum install -y terraform

  pre_build:
    commands:
      - git remote -v
      - git status
      - echo "Pipeline commit ${CODEBUILD_RESOLVED_SOURCE_VERSION}"

      - |
        if [ "${GIT_TAG}" != "." ]; then
          echo "Fetching tag ${GIT_TAG}"
          git fetch origin "refs/tags/${GIT_TAG}:refs/tags/${GIT_TAG}"
          git checkout "tags/${GIT_TAG}"

        elif [ "${GIT_COMMIT}" != "." ] && [ "${GIT_COMMIT}" != "${CODEBUILD_RESOLVED_SOURCE_VERSION}" ]; then
          echo "Fetching commit ${GIT_COMMIT}"
          git fetch origin "${GIT_COMMIT}"
          git checkout "${GIT_COMMIT}"

        elif [ "${GIT_BRANCH}" != "." ]; then
          echo "Fetching branch ${GIT_BRANCH}"
          git fetch origin "refs/heads/${GIT_BRANCH}:refs/remotes/origin/${GIT_BRANCH}"
          git checkout -B "${GIT_BRANCH}" "origin/${GIT_BRANCH}"
        fi

      - |
        GIT_HEAD=$(git rev-parse HEAD)
        echo "Checked out commit: ${GIT_HEAD}"

  build:
    commands:
      - terraform init -input=false
      - terraform validate
      - terraform plan -input=false -out=tfplan

artifacts:
  files:
    - "**/*"